# Generated by Django 5.1.7 on 2025-03-12 14:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_remove_category_slug_remove_view_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('question', ckeditor.fields.RichTextField()),
                ('answer_choice', models.JSONField()),
                ('corrrect_answer', models.CharField(max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tests', to='lesson.lesson')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_test', to='lesson.section')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
