# Generated by Django 5.1.7 on 2025-03-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
        ('lesson', '0007_alter_category_is_active_alter_comment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.user'),
        ),
    ]
