# Generated by Django 5.1.7 on 2025-03-13 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_news_remove_liketovideo_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/course images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/news images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media/course/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.mp4', '.avi', '.mov', '.mkv'], message='Faqat quyidagi formatlardagi fayllar qabul qilinadi: MP4, AVI, MOV, MKV.')]),
        ),
    ]
