# Generated by Django 5.1.7 on 2025-03-10 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998912345678' kabi formatda bo'lishi kerak.", regex='^\\+998\\d{8}$')], verbose_name='Phone_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_user_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Telegram user ID'),
        ),
    ]
