# Generated by Django 5.1.7 on 2025-03-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='SMS code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Phone_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram user ID'),
        ),
    ]
